environment:
  matrix:
    - nodejs_version: 6.2.0

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run lint
  - npm run build
  - npm run test:coverage
  - npm run coveralls