
language: node_js
node_js:
  - "4.2.1"
  - "0.12"
script:
  - npm run lint
  - npm run build
  - npm run test:coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js